name: RSpec

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: osanpo_record_2025_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: osanpo_record_2025_test
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.0"
          bundler-cache: true

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            mysqladmin ping -h 127.0.0.1 -proot && break
            sleep 2
          done



      - name: Prepare DB and Run RSpec
        run: |
          bundle exec rails db:prepare
          bundle exec rspec


